---
title: "Rugby Data"
author: "Marc Rovner"
date: "April 5, 2019"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(glmnet)
library(dplyr)
library(leaps)
library(MASS)
#gps=read.csv("gps2.csv")
#gps.move=read.csv("nonzero.csv")
games=read.csv("games.csv")
rpe=read.csv("rpe2.csv")
wellness=read.csv("wellness2.csv")
```

```{r}
head(games)
game.speed=read.csv("speedpergame.csv")
games=dplyr::rename(games,GameID=ï..GameID)


#gps.speed=dplyr::select(gps.move, PlayerID,Speed,GameID,Half)
#head(spread(gps.speed, key="PlayerID", value="Speed"))
#head(gps.speed)

games=merge(games,game.speed)
games=arrange(games,GameID,PlayerID)
write.csv(games,file="game_speed.csv")
head(games)
unique(games$Opponent)
```

```{r,eval=F}
game.speed.half1=read.csv("speedperhalf1.csv")
game.speed.half2=read.csv("speedperhalf2.csv")
game.speed.half=rbind(game.speed.half1,game.speed.half2)
games.half=merge(games,game.speed.half)
games.half=arrange(games.half,GameID,Half,PlayerID)

full.half=plyr::join(games.half,well.rpe,type="left")
full.half=dplyr::select(full.half,-BedTime,-WakeTime)
head(full.half)

full.mat=data.matrix(na.omit(full.half))
ridge.full=cv.glmnet(full.mat[,-c(1:3,5,10,11,13,14,31)],full.mat[,10], alpha=1,nfolds=5)
plot(ridge.full)

#run ridge with optimal lambda
full.l=ridge.full$lambda[which.min(ridge.full$cvm)]
full.best=glmnet(full.mat[,-c(1:3,5,10,11,13,14,31)],full.mat[,10],alpha=1,lambda=full.l)
ridge.pred=predict(full.best,s=full.l,newx=full.mat[,-c(1:3,5,10,11,13,14,31)])

MSE=mean((full.mat[,10]-ridge.pred)^2)
coef(full.best)
MSE
```

```{r}
well.rpe=read.csv("rpe_wellness.csv")
well.rpe$Date=as.Date(well.rpe$Date)
games$Date=as.Date(games$Date)
head(well.rpe)
head(games)
unique(well.rpe$Date)
unique(games$Date)
full=plyr::join(games,well.rpe,type="left")
full=dplyr::select(full,-BedTime,-WakeTime)
write.csv(full,file="full_dataset.csv")
head(full)
```

```{r}
full.mat=data.matrix(na.omit(full))
ridge.full=cv.glmnet(full.mat[,-c(1:3,5,8,10:13,30)],full.mat[,10], alpha=1,nfolds=5)
plot(ridge.full)

#run ridge with optimal lambda
full.l=ridge.full$lambda[which.min(ridge.full$cvm)]
full.best=glmnet(full.mat[,-c(1:3,5,8,10:13,30)],full.mat[,10],alpha=1,lambda=full.l)
ridge.pred=predict(full.best,s=full.l,newx=full.mat[,-c(1:3,5,8,10:13,30)])

MSE=mean((full.mat[,10]-ridge.pred)^2)
coef(full.best)
MSE
```

```{r}
full.lm=lm(ï..AvgSpeed~TeamPoints+Fatigue+Soreness+SleepHours+NutritionAdjustment,data=full)
summary(full.lm)
```

```{r}
head(wellness)
wellness=data.matrix(wellness)
ridge.well=cv.glmnet(wellness[,-c(1:3)],wellness[,3], alpha=1,nfolds=5)
plot(ridge.well)

#run ridge with optimal lambda
well.l=ridge.well$lambda[which.min(ridge.well$cvm)]
well.best=glmnet(wellness[,-c(1:3)],wellness[,3],alpha=1,lambda=well.l)
ridge.pred=predict(well.best,s=well.l,newx=wellness[,-c(1:3)])

MSE=mean((wellness[,3]-ridge.pred)^2)
coef(well.best)
MSE
```

```{r}

```


